services:
    db:
        image: mongo:latest
        restart: always
        user: mongodb
        ports:
            - "27017:27017"
        volumes:
            - ./datadir:/data/db
    webapp:
        build:
            context: .
            dockerfile: ./Dockerfile
        user: nobody
        environment:
            KERNEL_LIB_FETCH_TIMEOUT: "10"
        restart: always
        depends_on:
            - db
        ports:
            - "6543:6543"
            - "8087:8087"
